global:
  scrape_interval:     5s
  evaluation_interval: 15s
  scrape_timeout:      5s

scrape_configs:
- job_name: 'dev.local'
  static_configs:
  - targets: ['dev.local:8080']
- job_name: 'prometheus'
  static_configs:
  - targets: ['prometheus:9090']
- job_name: 'grafana'
  static_configs:
    - targets: ['grafana:3000']
- job_name: 'postgres_exporter'
  static_configs:
    - targets: ['postgres_exporter:9187']
- job_name: 'cadvisor'
  static_configs:
    - targets: ['cadvisor:8080']
- job_name: 'node-exporter'
  static_configs:
    - targets: ['node-exporter:9100']
