version: "2.2"
services:
  prometheus:
    image: prom/prometheus:v2.16.0
    restart: always
    ports:
      - "127.0.0.1:9090:9090"
    extra_hosts:
      - dev.local:${HOST_IP}
    volumes:
      - "./development/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "prometheus-data:/prometheus"
  postgres_exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@localhost:5432/db_name?sslmode=disable"
    ports:
      - "127.0.0.1:9187:9187"
    volumes:
      - "${PWD}/development/custom_queries.yml:/config/queries.yml"
    command:
      - "--extend.query-path=/config/queries.yml"
    depends_on:
      prometheus:
        condition: service_started
  grafana:
    image: grafana/grafana:6.6.2
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    depends_on:
      prometheus:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://grafana:3000/api/health"]
      interval: 1s
      timeout: 10s
      retries: 3

volumes:
  prometheus-data:
  grafana-data:
