version: "2.2"
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    restart: always
    ports:
      - "127.0.0.1:9090:9090"
    extra_hosts:
      - dev.local:${HOST_IP}
    volumes:
      - "./development/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "prometheus-data:/prometheus"
  postgres_exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@localhost:5432/db_name?sslmode=disable"
    ports:
      - "127.0.0.1:9187:9187"
    volumes:
      - "${PWD}/development/custom_queries.yml:/config/queries.yml:ro"
    command:
      - "--extend.query-path=/config/queries.yml"
  grafana:
    image: grafana/grafana:7.1.3
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret

volumes:
  prometheus-data:
  grafana-data:
