version: '2.2'
services:
  prometheus:
    image: prom/prometheus:v2.13.0
    restart: always
    ports:
      - "127.0.0.1:9090:9090"
    extra_hosts:
      - dev.local:${HOST_IP}
    volumes:
      - "./development/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "prometheus-data:/prometheus"
  postgres_exporter:
    image: wrouesnel/postgres_exporter:v0.5.1
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@localhost:5432/db_name?sslmode=disable"
    ports:
      - "127.0.0.1:9187:9187"
    depends_on:
      prometheus:
        condition: service_started
      # postgres:
      #   condition: service_healthy
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
  node-exporter:
    restart: always
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
  grafana:
    image: grafana/grafana:6.4.2
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    depends_on:
      prometheus:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://grafana:3000/api/health"]
      interval: 1s
      timeout: 10s
      retries: 3

volumes:
  prometheus-data:
  grafana-data:
