version: "2.2"
services:
  prometheus:
    image: prom/prometheus:v2.30.0
    restart: always
    mem_limit: 256m
    ports:
      - "127.0.0.1:9090:9090"
    extra_hosts:
      - dev.local:${HOST_IP}
    volumes:
      - "./development/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "prometheus-data:/prometheus"
  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    restart: always
    mem_limit: 64m
    environment:
      DATA_SOURCE_URI: postgres/dbname
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: postgres
    ports:
      - "127.0.0.1:9187:9187"
    volumes:
      - "${PWD}/development/custom_queries.yml:/config/queries.yml:ro"
    command:
      - "--extend.query-path=/config/queries.yml"
  grafana:
    image: grafana/grafana:8.1.5
    restart: always
    mem_limit: 128m
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret

volumes:
  prometheus-data:
  grafana-data:
